### PR TITLE
Use bunnies.io to serve bunnies on 400 and 500 pages

### PR DESCRIPTION
**Pull request by voxelcarrot**
As title describes.

### CODE REVIEW

**Comment by CraigSnowden** [comment]
:shipit:

**Comment by voxelcarrot** [comment]
http://i.imgur.com/kWSsa6N.png :+1:

**Comment by neanias** [comment]
I'll also build it when I get back and then probably approve and merge

**Comment by CraigSnowden** [comment]
"Build"

**Comment by neanias** [comment]
Well, I'll try and getting running, God only knows if it'll work this time

**Comment by neanias** [comment]
After much swearing and threatening to kill @R2ZER0, we've got it running. Merged

**Comment by neanias** [comment]
Oops

**Pull request merged**
