### PR TITLE
Merge recent documentation and IRC changes to stable

### PR DESCRIPTION
**Pull request by lopcode**
Looking through the diff, no functional change. You should try it first.

### CODE REVIEW

**Comment by R2ZER0** [comment]
Woah, looks like there is a lot more going on here than just irc/documentation

**Comment by lopcode** [comment]
I see whitespace changes and documentation changes alone? Which bit are you referring to?

EDIT: That and explicitly using Python 2, but it wouldn't have worked without it anyway.

**Comment by neanias** [comment]
@carrotengineer Good work on putting a better requirements layout into the README btw

**Comment by Wyldern** [comment]
I can't see any reason _not_ to merge this; @R2ZER0 gerroff your butt :shipit: =p

**Pull request merged**
